import Head from 'next/head';
import MonsterMenu from 'src/components/MonsterMenu/MonsterMenu';
import SelectedScreen from 'src/components/SelectedScreen/SelectedScreen';
import MusicManager from 'src/components/MusicManager/MusicManager';

export default function Home() {
	return (
		<div className="container">
			<Head>
				<title>Next TypeScript Starter</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MusicManager></MusicManager>

			<main className="main">
				<h1 className="theTitle">Musical Monsters</h1>
				<SelectedScreen></SelectedScreen>
				<MonsterMenu></MonsterMenu>
			</main>
		</div>
	);
}
