import Head from 'next/head';
import Timer from 'src/components/Timer/Timer';
import MonsterMenu from 'src/components/MonsterMenu/MonsterMenu';
import { monstersRepo } from '../helpers/monsters-repo';
import { Monster } from 'utils/types';
import RealMonster from 'src/components/Monster/Monster';

// export const getStaticProps = async () => {
// 	return {
// 		props: {
// 			monsters,
// 		},
// 	};
// };

export default function Home() {
	let monsterList: Monster[] = monstersRepo.getAll();

	return (
		<div className="container">
			<Head>
				<title>Next TypeScript Starter</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Timer></Timer>

			<main className="main">
				<h1 className="title">Musical Monsters</h1>
				<MonsterMenu></MonsterMenu>
				<section className="grid">
					{monsterList.map((monster) => (
						<RealMonster
							id={monster.id}
							name={monster.name}
							picturePath={monster.picturePath}
							soundPath={monster.soundPath}
						></RealMonster>
					))}
				</section>
			</main>
		</div>
	);
}
